blog:
  image: ghost
  ports:
    - 2368:2368
  links:
    - mail
    - postgres
    - ghostdb
  volumes_from:
    - blogdata
  env_file:
    - environment.list

blogdata:
  build: ./ghost-data/image

ghostdb:
  build: ./ghost-db/image
  links:
    - postgres
  volumes:
    - ./ghost-db/volumes/sql:/sql

mail:
  image: schickling/mailcatcher
  ports:
    - "1080:1080"
  expose:
    - "1025"

postgres:
  image: postgres:9.4
  links:
    - postgresdata
  volumes_from:
    - postgresdata
  env_file:
      - environment.list
  expose:
      - "5432"

postgresdata:
  build: ./postgres-data/image