blog:
  image: ghost
  restart: always
  ports:
    - 2368:2368
  links:
    - postgres
  volumes_from:
    - blogdata
  env_file:
    - ../credentials/website/production.list

blogdata:
  build: ./images/ghost-data

postgres:
  image: postgres
  restart: always
  volumes_from:
      - postgresdata
  expose:
        - "5432"
  env_file:
      - ../credentials/website/production.list

postgresdata:
  build: ./images/postgres-data