# Development Ghost Deployment
# Requires docker-compose 1.2
blog:
  extends:
    file: ./compose/ghost.yml
    service: blog
  links:
    - mail
    - postgres
    - ghostdb
  volumes_from:
    - blogdata

blogdata:
  extends:
    file: ./compose/ghost.yml
    service: blogdata

ghostdb:
  extends:
    file: ./compose/ghost.yml
    service: ghostdb
  links:
    - postgres
  volumes:
    - ./ghost-db/volumes/sql:/sql

postgres:
  extends:
    file: ./compose/postgres.yml
    service: postgres
  volumes_from:
    - postgresdata

postgresdata:
  extends:
    file: ./compose/postgres.yml
    service: postgresdata

# MailCatcher for handling email during development
mail:
  image: schickling/mailcatcher
  ports:
    - "1080:1080"
  expose:
    - "1025"